# Generated by Django 4.2 on 2024-12-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_ind", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="robot",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="robots.robotmodel",
            ),
        ),
    ]
