# Generated by Django 4.2 on 2024-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
