# Generated by Django 4.2 on 2024-12-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0003_robot_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="robots",
                to="robots.robotmodel",
            ),
        ),
    ]
